version: "3.8"
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=dd_db

  backend:
    image: ananya117/backend:latest
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/dd_db
  frontend:
    image: ananya117/frontend:latest
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
